spring:
  application:
    name: zuul-server
eureka:
  client:
    instance:
      preferIpAddress: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
    registerWithEureka: true
server:
  port: 8999
  servlet:
    context-path: /cloud
zuul:
  routes:
    eureka-client-1: /client-1/**
    eureka-client-2: /client-2/**
  sensitiveHeaders: Cookie, Set-Cookie